version: "3.1"
volumes:
  grafana:
services:

  agent:
    image: grafana/agent:main
    ports:
      - "4318:4318"
    volumes:
      - "${PWD}/agent/config.yaml:/etc/agent/agent.yaml"

  dummy-server:
    build: ./src
    ports:
      - "4000:4000"
      - "80:80"
    depends_on:
      - loki

  grafana:
    image: grafana/grafana-oss:9.0.3
    restart: on-failure
    volumes:
      - "./grafana/definitions:/var/lib/grafana/dashboards"
      - "./grafana/provisioning:/etc/grafana/provisioning"
    ports:
      - "3000:3000"
    environment:
      - GF_FEATURE_TOGGLES_ENABLE=tempoSearch
  loki:
    image: qxip/qryn:latest
    restart: on-failure
    ports:
      - "3100:3100"
    environment:
      - CLICKHOUSE_SERVER=clickhouse
      - CLICKHOUSE_DB=uptrace
    
  clickhouse:
    image: 'clickhouse/clickhouse-server:latest'
    restart: on-failure
    environment:
      - CLICKHOUSE_DB=qryn
    healthcheck:
      test: ['CMD', 'wget', '--spider', '-q', 'localhost:8123/ping']
      interval: 1s
      timeout: 1s
      retries: 30
