version: "3.1"
volumes:
  grafana:
services:

  agent:
    image: grafana/agent:main
    ports:
      - "4318:4318"
    volumes:
      - "${PWD}/agent/config.yaml:/etc/agent/agent.yaml"

  dummy-server:
    build: ./src
    ports:
      - "4000:4000"
      - "80:80"
    depends_on:
      - tempo
      - loki

  grafana:
    image: grafana/grafana
    restart: on-failure
    volumes:
      - "./grafana/definitions:/var/lib/grafana/dashboards"
      - "./grafana/provisioning:/etc/grafana/provisioning"
    ports:
      - "3000:3000"
    environment:
      - GF_FEATURE_TOGGLES_ENABLE=tempoSearch
  loki:
    image: qxip/cloki
    restart: on-failure
    ports:
      - "3100:3100"
    environment:
      - CLICKHOUSE_SERVER=clickhouse
      - CLICKHOUSE_DB=uptrace
    
  tempo:
    image: uptrace/uptrace
    restart: on-failure
    ports:
      - "4317:14317"  # TEMPO API
      - '14317:14317' # OTLP
      - '14318:14318' # UI and HTTP API
    volumes:
      - ./uptrace/uptrace.yml:/etc/uptrace/uptrace.yml

  clickhouse:
    image: 'yandex/clickhouse-server:latest'
    restart: on-failure
    environment:
      - CLICKHOUSE_DB=uptrace
    healthcheck:
      test: ['CMD', 'wget', '--spider', '-q', 'localhost:8123/ping']
      interval: 1s
      timeout: 1s
      retries: 30
